INSERT INTO tb_usuarios (nome, email) 
VALUES ('rafael', 'rafael@gmail.com'),
('camila', 'camila@gmail.com'),
('luciano', 'luciano@gmail.com'),
('ricardo', 'ricardo@gmail.com'),
('maria', 'maria@gmail.com'),
('marcelo', 'marcelo@gmail.com'),
('eduardo', 'eduardo@gmail.com'),
('luana', 'luana@gmail.com'),
('flavia', 'flavia@gmail.com'),
('sandra', 'sandra@gmail.com');

INSERT INTO tb_tecnologias (usuario_id, nome_tecnologia) 
VALUES (1, 'JavaScript'),
(1, 'HTML'),
(1, 'CSS'),
(2, 'HTML'),
(2, 'CSS'),
(2, 'git'),
(3, 'NodeJS'),
(3, 'JavaScript'),
(3, 'MySQL'),
(4, 'Python'),
(4, 'Flask'),
(3, 'MySQL'),
(5, 'C'),
(5, 'git'),
(5, 'GitHub'),
(6, 'MySQL'),
(6, 'PHP'),
(7, 'git'),
(7, 'HTML'),
(7, 'CSS'),
(8, 'JAVA'),
(8, 'Python'),
(8, 'C'),
(9, 'HTML'),
(9, 'JavaScript'),
(9, 'NodeJS'),
(10, 'Python'),
(10, 'Django');
